#!/bin/sh

handle() {
	if [ -f "$1" ];
	then
		highlight "$1" -O ansi --force
	elif [ -d "$1" ];
	then
		tree "$1" -La 1
	fi
}

# Calculate where the image should be placed on the screen.
cols=`expr $(tput cols) - 4`
lins=`expr $(tput lines) - 4`
img="timg -g${cols}x${lins} -C "

case "$1" in
    *.bmp|*.svg|*.png|*.jpg|*.jpeg|*.mkv|*.mp4|*.m4v) $img "$1";;
    *.md) mdcat "$1";;
    *.pdf) pdftotext "$1" -;;
    *.tar.gz) tar -ztvf "$1";;
    *.tar.bz2) tar -jtvf "$1";;
    *.tar) tar -tvf "$1";;
    *.rar) unrar l "$1";;
    *.7z|*.zip) 7z l "$1";;
    #*.html|*.xml) w3m -dump "$1";;
    #*.zsh*|*.bash*|*.git*) pistol "$1";;
	*.torrent) transmission-show "$1";;
	*.iso) iso-info --no-header -l "$1";;
	*.csv) cat "$1" | sed s/,/\\n/g ;;
	*.pdf) #requiere poppler poppler-utils
		CACHE=$(mktemp /tmp/thumbcache.XXXXX)
		pdftoppm -png -singlefile "$1" "$CACHE"
		$img "$CACHE.png"
		;;
	*.epub)
		CACHE=$(mktemp /tmp/thumbcache.XXXXX) #requiere gnome-epub-thumbnailer
		gnome-epub-thumbnailer "$1" "$CACHE"
		$img "$CACHE"
		;;
	*.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac) mediainfo "$1";;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx) $img "$1";;
    *) handle "$1" ;;
esac

